[package]
name = "easyrazer"
version = "0.1.0"
edition.workspace = true

[build-dependencies]
tauri-build = { version = "2", features = [] }

[dependencies]
tauri = { version = "2", features = ["tray-icon"] }
tauri-plugin-single-instance = "2"
serde = { version = "1", features = ["derive"] }
serde_json = "1"
hidapi = "2"
razer-core = { path = "../../crates/core", features = ["hid"] }
windows-sys = { version = "0.61", features = ["Win32_UI_Input_KeyboardAndMouse", "Win32_UI_WindowsAndMessaging", "Win32_System_Power", "Win32_UI_Shell", "Win32_System_Registry", "Win32_System_Diagnostics_ToolHelp"] }
