[package]
name = "easyrazer"
version = "0.1.0"
edition.workspace = true

[build-dependencies]
tauri-build = { version = "2", features = [] }

[dependencies]
tauri = { version = "2", features = [] }
serde = { version = "1", features = ["derive"] }
hidapi = "2"
razer-core = { path = "../../crates/core", features = ["hid"] }
